# Copyright (C) 2024 Ohad Lutzky <lutzky@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "zsnapfree"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
human_bytes = "0.4.3"
indoc = "2.0.5"
pretty_assertions = "1.4.0"
ratatui = "0.30.0"
